### ISSUE TITLE
Creating change set fails with internal error

### ISSUE THREAD

**Issue by Nitjsefni7** [mongodb/mongodbatlas-cloudformation-resources#189]
### CloudFormation Template 

```
AWSTemplateFormatVersion: 2010-09-09
Conditions:
  PROD:
    Fn::Equals:
    - Ref: Environment
    - PROD
Description: MongoDB Atlas
Metadata:
  StackName: MongoDBAtlas
Outputs:
  AtlasAPISecretName:
    Description: Cluster Id is also a name for secret with API keys
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-AtlasAPISecretName
    Value:
      Ref: Cluster
  ConnectionStringSrv:
    Description: Cluster connection strings
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-ConnectionStringSrv
    Value:
      Fn::GetAtt:
      - Cluster
      - ConnectionStrings.StandardSrv
  Role:
    Description: ARN of AWS IAM Role database cluster access
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-Role
    Value:
      Fn::GetAtt:
      - IAMRole
      - Arn
  SecretArn:
    Description: ARN of MongoDB Atlas root user secret
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-SecretArn
    Value:
      Ref: Secret
Parameters:
  BuildDir:
    Description: Folder name with application build
    Type: String
  DataDogApiKey:
    Description: DataDog api key for lambda logs forwarding
    NoEcho: true
    Type: String
  Environment:
    Description: Stack creates lambdas with prefixes taken from environment variable
      value
    Type: String
  NetworkEnv:
    Description: Prefix used to specify the network name
    Type: String
  OrganizationId:
    Description: MongoDB Atlas Organization Id
    Type: String
  PrivateKey:
    Description: MongoDB Atlas Private API Key
    NoEcho: true
    Type: String
  PublicKey:
    Description: MongoDB Atlas Public API Key
    NoEcho: true
    Type: String
  Version:
    Description: Current version
    Type: String
Resources:
  AtlasManager:
    Properties:
      PrivateKey:
        Ref: PrivateKey
      ProjectId:
        Ref: Project
      PublicKey:
        Ref: PublicKey
      ServiceToken:
        Fn::GetAtt:
        - AtlasManagerLambda
        - Arn
      VpcPeeringId:
        Ref: NetworkPeering
    Type: Custom::MongoDBAtlasManager
    Version: "0.1"
  AtlasManagerLambda:
    DependsOn:
    - AtlasManagerLambdaRole
    Properties:
      Code:
        S3Bucket:
          Fn::Transform:
            Name: String
            Parameters:
              InputString:
                Fn::Sub: ${Environment}.sc.assets
              Operation: BuildBucket
        S3Key:
          Fn::Sub: mongodbatlas/${BuildDir}/lambdas/atlas_manager/bootstrap.zip
      Description: AWS Lambda function
      Environment:
        Variables:
          DD_API_KEY:
            Ref: DataDogApiKey
          DD_ENV:
            Ref: Environment
          DD_VERSION:
            Ref: Version
          Environment:
            Ref: Environment
      FunctionName:
        Fn::Sub: ${Environment}-AtlasManager-Lambda
      Handler: bootstrap
      Layers:
      - Fn::If:
        - PROD
        - arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension:35
        - Ref: AWS::NoValue
      MemorySize: 256
      Role:
        Fn::GetAtt:
        - AtlasManagerLambdaRole
        - Arn
      Runtime: provided.al2
      Timeout: 900
      TracingConfig:
        Mode: Active
      VpcConfig:
        SecurityGroupIds:
        - Fn::ImportValue:
            Fn::Sub: ${NetworkEnv}-Network-PrivateNatSecurityGroupId
        SubnetIds:
          Fn::Split:
          - ','
          - Fn::ImportValue:
              Fn::Sub: ${NetworkEnv}-Network-PrivateNatSubnetIds
    Type: AWS::Lambda::Function
  AtlasManagerLambdaRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action:
            - ec2:DescribeVpcPeeringConnections
            Effect: Allow
            Resource: '*'
          - Action:
            - ec2:AcceptVpcPeeringConnection
            Effect: Allow
            Resource:
            - Fn::Sub: arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:vpc/*
            - Fn::Sub: arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:vpc-peering-connection/*
          Version: 2012-10-17
        PolicyName: HandleVPCPeeringConnection
      RoleName:
        Fn::Sub: ${Environment}-AtlasManager-LambdaRole
      Tags:
      - Key: env
        Value:
          Fn::Sub: ${Environment}
      - Key: service
        Value: mongodbatlas
      - Key: version
        Value:
          Fn::Sub: ${Version}
    Type: AWS::IAM::Role
  Cluster:
    Properties:
      ApiKeys:
        PrivateKey:
          Ref: PrivateKey
        PublicKey:
          Ref: PublicKey
      BackupEnabled: true
      ClusterType: REPLICASET
      DiskSizeGB: 50
      MongoDBMajorVersion: "6.0"
      Name:
        Fn::Sub: ${Environment}-SmartMerchant-Cluster
      PitEnabled: false
      ProjectId:
        Ref: Project
      ReplicationSpecs:
      - AdvancedRegionConfigs:
        - AutoScaling:
            DiskGB:
              Enabled: true
          ElectableSpecs:
            EbsVolumeType: PROVISIONED
            InstanceSize: M10
            NodeCount: 3
          Priority: 7
          RegionName: US_EAST_1
        NumShards: 0
      TerminationProtectionEnabled: true
    Type: MongoDB::Atlas::Cluster
    Version: "0.1"
  IAMRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Action: sts:AssumeRole
          Effect: Allow
          Principal:
            AWS:
              Fn::Sub: arn:aws:iam::${AWS::AccountId}:root
        Version: 2012-10-17
      RoleName:
        Fn::Sub: ${Environment}-MongoDBAtlas-Role
    Type: AWS::IAM::Role
  IAMRoleDatabaseUser:
    Properties:
      AWSIAMType: ROLE
      ApiKeys:
        PrivateKey:
          Ref: PrivateKey
        PublicKey:
          Ref: PublicKey
      DatabaseName: $external
      ProjectId:
        Ref: Project
      Roles:
      - DatabaseName: admin
        RoleName: readWriteAnyDatabase
      Username:
        Fn::GetAtt:
        - IAMRole
        - Arn
    Type: MongoDB::Atlas::DatabaseUser
    Version: "0.1"
  NetworkPeering:
    Properties:
      AccepterRegionName:
        Fn::Sub: ${AWS::Region}
      ApiKeys:
        PrivateKey:
          Ref: PrivateKey
        PublicKey:
          Ref: PublicKey
      AwsAccountId:
        Fn::Sub: ${AWS::AccountId}
      ProjectId:
        Ref: Project
      RouteTableCIDRBlock:
        Fn::ImportValue:
          Fn::Sub: ${NetworkEnv}-Network-PrivateVPCCidrBlock
      VpcId:
        Fn::ImportValue:
          Fn::Sub: ${NetworkEnv}-Network-PrivateVPCId
    Type: MongoDB::Atlas::NetworkPeering
    Version: "0.1"
  PasswordDatabaseUser:
    Properties:
      AWSIAMType: NONE
      ApiKeys:
        PrivateKey:
          Ref: PrivateKey
        PublicKey:
          Ref: PublicKey
      DatabaseName: admin
      Password:
        Fn::Join:
        - ""
        - - '{{resolve:secretsmanager:'
          - Ref: Secret
          - :SecretString:password}}
      ProjectId:
        Ref: Project
      Roles:
      - DatabaseName: admin
        RoleName: readWriteAnyDatabase
      Username:
        Fn::Join:
        - ""
        - - '{{resolve:secretsmanager:'
          - Ref: Secret
          - :SecretString:username}}
    Type: MongoDB::Atlas::DatabaseUser
    Version: "0.1"
  PrivateNatVPCRoute:
    DependsOn:
    - AtlasManager
    Properties:
      DestinationCidrBlock:
        Fn::GetAtt:
        - AtlasManager
        - AtlasCidr
      RouteTableId:
        Fn::ImportValue:
          Fn::Sub: ${NetworkEnv}-Network-PrivateNatVPCRouteTableId
      VpcPeeringConnectionId:
        Fn::GetAtt:
        - AtlasManager
        - VpcPeeringConnectionID
    Type: AWS::EC2::Route
  PrivateVPCRoute:
    DependsOn:
    - AtlasManager
    Properties:
      DestinationCidrBlock:
        Fn::GetAtt:
        - AtlasManager
        - AtlasCidr
      RouteTableId:
        Fn::ImportValue:
          Fn::Sub: ${NetworkEnv}-Network-PrivateVPCRouteTableId
      VpcPeeringConnectionId:
        Fn::GetAtt:
        - AtlasManager
        - VpcPeeringConnectionID
    Type: AWS::EC2::Route
  Project:
    Properties:
      ApiKeys:
        PrivateKey:
          Ref: PrivateKey
        PublicKey:
          Ref: PublicKey
      Name:
        Fn::Sub: ${Environment}-SmartMerchant
      OrgId:
        Ref: OrganizationId
    Type: MongoDB::Atlas::Project
    Version: "0.1"
  ProjectIPAccessList:
    DependsOn:
    - NetworkPeering
    - AtlasManager
    Properties:
      AccessList:
      - AwsSecurityGroup:
          Fn::ImportValue:
            Fn::Sub: ${NetworkEnv}-Network-PrivateSecurityGroupId
        Comment: Access for private security group.
        ProjectId:
          Ref: Project
      - AwsSecurityGroup:
          Fn::ImportValue:
            Fn::Sub: ${NetworkEnv}-Network-PrivateNatSecurityGroupId
        Comment: Access for private NAT security group.
        ProjectId:
          Ref: Project
      ApiKeys:
        PrivateKey:
          Ref: PrivateKey
        PublicKey:
          Ref: PublicKey
      ProjectId:
        Ref: Project
    Type: MongoDB::Atlas::ProjectIpAccessList 
    Version: "0.1"
  Secret:
    Properties:
      Description: Secret for MongoDB Atlas cluster
      GenerateSecretString:
        ExcludePunctuation: true
        GenerateStringKey: password
        PasswordLength: 16
        SecretStringTemplate:
          Fn::Join:
          - ""
          - - '{"username":"root",'
            - '"connectionString":"'
            - Fn::GetAtt:
              - Cluster
              - ConnectionStrings.StandardSrv
            - '"}'
      Name:
        Fn::Sub: ${Environment}/MongoDBAtlas-Secret
    Type: AWS::SecretsManager::Secret
```

### Steps to Reproduce

Create change set using either CLI or GUI.
Command for CLI:
```
aws cloudformation create-change-set --stack-name ${ENV}-MongoDBAtlas \
--template-url url --parameters \
ParameterKey=Environment,ParameterValue=${ENV} ParameterKey=NetworkEnv,ParameterValue=${NETWORK_ENV} \
ParameterKey=Version,ParameterValue=${VERSION} ParameterKey=BuildDir,ParameterValue=${BUILD_DIR} \
ParameterKey=PublicKey,UsePreviousValue=true \
ParameterKey=PrivateKey,UsePreviousValue=true \
ParameterKey=OrganizationId,UsePreviousValue=true \
ParameterKey=DataDogApiKey,UsePreviousValue=true \
--no-use-previous-template \
--change-set-name MongoDBAtlas-ChangeSet${BITBUCKET_BUILD_NUMBER} \
--capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM
```

### Expected Behavior

Change set creation should ends with success or describe what went wrong.

### Actual Behavior

Returned response is 
`There was an error creating this change set
Internal Failure`
Execution status: UNAVAILABLE
Status reason: Internal Failure

**Comment by lee-wilkins** [comment]
@Nitjsefni7 - Not sure if its helpful, but i've been experiencing the same issue recently. My problem was that many of the official guidance you can find for actually setting up the custom resources in the first place is out of date. I had referenced MongoDBs own getting started guide and installed the custom resources using a script. This added out of date resources and caused me all sorts of issues.

Make sure you only install the resources as Third Party Public resources, either via cloudformation (and reference the type name rather than a zip) or directly via the console to ensure you have the most up to date.

For example our custom resources are now installed in a separate stack that references the latest minor version of each resource as such:

  ```
RegisterProjectType:
    Type: "AWS::CloudFormation::TypeActivation"
    Properties:
      AutoUpdate: true
      TypeName: 'MongoDB::Atlas::Project'
      Type: 'RESOURCE'
      PublisherId: !Ref MongoDBPublisherId
      ExecutionRoleArn: 
        Fn::ImportValue: 
          !Join [
            ":",
            [!Ref "IamStackName", "CloudformationExecutionRoleArn"],
          ]
```

**Comment by Nitjsefni7** [comment]
Thank you for the response. We are registering custom resources using CloudFormation CLI commands, so I assume they are up-to-date.

**Comment by Adelmar92** [comment]
Hi @Nitjsefni7 you have a lead on witch resource is the one that is throwing the error?

**Comment by Adelmar92** [comment]
@Nitjsefni7 can you please try activating the Atlas Resources using this excecution role?[role](https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/master/examples/execution-role.yaml)

**Comment by Nitjsefni7** [comment]
So, I have changed my current policy assigned to the role which is set to be execution role for registered custom resources from
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "secretsmanager:GetSecretValue",
                "secretsmanager:DescribeSecret",
                "secretsmanager:PutSecretValue",
                "secretsmanager:CreateSecret",
                "secretsmanager:UpdateSecretVersionStage"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```
to
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "secretsmanager:CreateSecret",
                "secretsmanager:DescribeSecret",
                "secretsmanager:GetSecretValue",
                "secretsmanager:PutSecretValue",
                "secretsmanager:UpdateSecretVersionStage",
                "ec2:CreateVpcEndpoint",
                "ec2:DeleteVpcEndpoints",
                "cloudformation:CreateResource",
                "cloudformation:DeleteResource",
                "cloudformation:GetResource",
                "cloudformation:GetResourceRequestStatus",
                "cloudformation:ListResources",
                "cloudformation:UpdateResource",
                "iam:AttachRolePolicy",
                "iam:CreateRole",
                "iam:DeleteRole",
                "iam:GetRole",
                "iam:GetRolePolicy",
                "iam:ListAttachedRolePolicies",
                "iam:ListRolePolicies",
                "iam:PutRolePolicy"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```
I've skipped the `secretsmanager:CreateSecretInput` because I've received an error
`Invalid Action: The action secretsmanager:CreateSecretInput does not exist.`

After this I still cannot create change set. 
But, as this can be important, resources were registered using the old role, I've made changes to the role with resources already registered. As unregistering and registering resources again will be a bit difficult for me (I've already created stacks using them), I'd like to ask first If You think this can make a difference - registering them with a new role and not just updating it afterward.

**Comment by Adelmar92** [comment]
@Nitjsefni7 im trying to isolate the issue and just be sure that is not an Atlas resource error...
ive isolated the Atlas resources, this is working for me, can we please try if this stack works?
``` yaml
AWSTemplateFormatVersion: 2010-09-09
Conditions:
  PROD:
    Fn::Equals:
    - Ref: Environment
    - PROD
Description: MongoDB Atlas
Metadata:
  StackName: MongoDBAtlas
Parameters:
  Environment:
    Description: Stack creates lambdas with prefixes taken from environment variable
      value
    Type: String
  OrganizationId:
    Description: MongoDB Atlas Organization Id
    Type: String
  PrivateKey:
    Description: MongoDB Atlas Private API Key
    NoEcho: true
    Type: String
  PublicKey:
    Description: MongoDB Atlas Public API Key
    NoEcho: true
    Type: String
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: VPC-ID of your existing Virtual Private Cloud (VPC) which you wish to peer to your new MongoDB Atlas cluster. This is the VPC that your application uses usually.
  RouteTableCIDRBlock:
    Type: String
    Description: CIDR block to use for your VPC Peering.
Resources:
  Project:
    Properties:
      ApiKeys:
        PrivateKey:
          Ref: PrivateKey
        PublicKey:
          Ref: PublicKey
      Name:
        Fn::Sub: ${Environment}-SmartMerchant
      OrgId:
        Ref: OrganizationId
    Type: MongoDB::Atlas::Project
    Version: "0.1"
  Cluster:
    Properties:
      ApiKeys:
        PrivateKey:
          Ref: PrivateKey
        PublicKey:
          Ref: PublicKey
      BackupEnabled: true
      ClusterType: REPLICASET
      DiskSizeGB: 50
      MongoDBMajorVersion: "6.0"
      Name:
        Fn::Sub: ${Environment}-SmartMerchant-Cluster
      PitEnabled: false
      ProjectId:
        Ref: Project
      ReplicationSpecs:
      - AdvancedRegionConfigs:
        - AutoScaling:
            DiskGB:
              Enabled: true
          ElectableSpecs:
            EbsVolumeType: PROVISIONED
            InstanceSize: M10
            NodeCount: 3
          Priority: 7
          RegionName: US_EAST_1
        NumShards: 0
      TerminationProtectionEnabled: true
    Type: MongoDB::Atlas::Cluster
    Version: "0.1"
  IAMRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Action: sts:AssumeRole
          Effect: Allow
          Principal:
            AWS:
              Fn::Sub: arn:aws:iam::${AWS::AccountId}:root
        Version: 2012-10-17
      RoleName:
        Fn::Sub: ${Environment}-MongoDBAtlas-Role
    Type: AWS::IAM::Role
  IAMRoleDatabaseUser:
    Properties:
      AWSIAMType: ROLE
      ApiKeys:
        PrivateKey:
          Ref: PrivateKey
        PublicKey:
          Ref: PublicKey
      DatabaseName: $external
      ProjectId:
        Ref: Project
      Roles:
      - DatabaseName: admin
        RoleName: readWriteAnyDatabase
      Username:
        Fn::GetAtt:
        - IAMRole
        - Arn
    Type: MongoDB::Atlas::DatabaseUser
    Version: "0.1"
  NetworkPeering:
    Properties:
      AccepterRegionName:
        Fn::Sub: ${AWS::Region}
      ApiKeys:
        PrivateKey:
          Ref: PrivateKey
        PublicKey:
          Ref: PublicKey
      AwsAccountId:
        Fn::Sub: ${AWS::AccountId}
      ProjectId:
        Ref: Project
      RouteTableCIDRBlock: !Ref "RouteTableCIDRBlock"
      VpcId: !Ref "VPC"
    Type: MongoDB::Atlas::NetworkPeering
    Version: "0.1"
  Secret:
    Properties:
      Description: Secret for MongoDB Atlas cluster
      GenerateSecretString:
        ExcludePunctuation: true
        GenerateStringKey: password
        PasswordLength: 16
        SecretStringTemplate:
          Fn::Join:
          - ""
          - - '{"username":"root",'
            - '"connectionString":"'
            - Fn::GetAtt:
              - Cluster
              - ConnectionStrings.StandardSrv
            - '"}'
      Name:
        Fn::Sub: ${Environment}/MongoDBAtlas-Secret
    Type: AWS::SecretsManager::Secret
  PasswordDatabaseUser:
    Properties:
      AWSIAMType: NONE
      ApiKeys:
        PrivateKey:
          Ref: PrivateKey
        PublicKey:
          Ref: PublicKey
      DatabaseName: admin
      Password:
        Fn::Join:
        - ""
        - - '{{resolve:secretsmanager:'
          - Ref: Secret
          - :SecretString:password}}
      ProjectId:
        Ref: Project
      Roles:
      - DatabaseName: admin
        RoleName: readWriteAnyDatabase
      Username:
        Fn::Join:
        - ""
        - - '{{resolve:secretsmanager:'
          - Ref: Secret
          - :SecretString:username}}
    Type: MongoDB::Atlas::DatabaseUser
    Version: "0.1"
  AtlasProjectIPAccessList:
```
