### ISSUE TITLE
MongoDB::Atlas::PrivateEndpoint schema incorrectly structure to only allow 1-1 connection between vpc and subnet

### ISSUE THREAD

**Issue by lee-wilkins** [mongodb/mongodbatlas-cloudformation-resources#191]
The  MongoDB::Atlas::PrivateEndpoint custom resource schema seems to be incorrectly structured to only allow one subnetId per VPC when setting up the private endpoint.

In our use case we have an ECS Cluster with tasks split across three subnets. I want to create a Private Endpoint that links to the three subnets. However the current schema structure is 1-1 and therefore we end up setting up 3 private endpoints, one for each subnet.

This should replicate the functionality that is available in the Atlas console. i.e. attaching multiple subnets to a VPC when creating the Private Endpoint as seen in the screenshot below:
![Screenshot 2023-01-18 at 4 01 40 PM](https://user-images.githubusercontent.com/19402472/213115970-3d45ce38-6445-478b-95b4-6bbc965a65b8.png)

Our current solution looks like this:

```
 AtlasPrivateEndpoint:
    DependsOn: AtlasProject
    Type: MongoDB::Atlas::PrivateEndpoint
    Properties:
      GroupId: !Ref "AtlasProject"
      ApiKeys:
        PublicKey:  !Ref "PublicKey"
        PrivateKey: !Ref "PrivateKey"
      Region: !Ref "ClusterRegion"
      PrivateEndpoints:
      - VpcId: 
          Fn::ImportValue: !Join [':', [!Ref 'NetworkStackName', 'BEVPC']]
        SubnetId: 
          Fn::ImportValue: !Join [':', [!Ref 'NetworkStackName', 'BEPublicSubnet1']]
      - VpcId: 
          Fn::ImportValue: !Join [':', [!Ref 'NetworkStackName', 'BEVPC']]
        SubnetId: 
          Fn::ImportValue: !Join [':', [!Ref 'NetworkStackName', 'BEPublicSubnet2']]
      - VpcId: 
          Fn::ImportValue: !Join [':', [!Ref 'NetworkStackName', 'BEVPC']]
        SubnetId: 
          Fn::ImportValue: !Join [':', [!Ref 'NetworkStackName', 'BEPublicSubnet3']]
```

However, as mentioned this sets up 3 private endpoints because the schema is defined as such https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/master/cfn-resources/private-endpoint/docs/privateendpoint.md

Expected Behaviour:
We should be able to attach multiple subnetIds to a singular VPCId from cloudformation, i would expect the use case above would then look something similar to this:

```
 AtlasPrivateEndpoint:
    DependsOn: AtlasProject
    Type: MongoDB::Atlas::PrivateEndpoint
    Properties:
      GroupId: !Ref "AtlasProject"
      ApiKeys:
        PublicKey:  !Ref "PublicKey"
        PrivateKey: !Ref "PrivateKey"
      Region: !Ref "ClusterRegion"
      PrivateEndpoints:
      - VpcId: 
          Fn::ImportValue: !Join [':', [!Ref 'NetworkStackName', 'BEVPC']]
          -SubnetIds: 
            Fn::ImportValue: !Join [':', [!Ref 'NetworkStackName', 'BEPublicSubnet1']]
            Fn::ImportValue: !Join [':', [!Ref 'NetworkStackName', 'BEPublicSubnet2']]
            Fn::ImportValue: !Join [':', [!Ref 'NetworkStackName', 'BEPublicSubnet3']]
``
