### ISSUE TITLE
MongoDB::Atlas::ServerlessInstance unable to output connection strings

### ISSUE THREAD

**Issue by lee-wilkins** [mongodb/mongodbatlas-cloudformation-resources#200]
The MongoDB::Atlas::ServerlessInstance schema is currently unable to output the connection strings.

### Expected Behavior
Required to be able to export the srv connection strings for consumption in another template.

As per documentation i have the following setup:

```
AtlasServerless:
    Type: MongoDB::Atlas::ServerlessInstance
    DependsOn: AtlasProject
    Properties:
      ApiKeys:
        PublicKey:  !Ref "PublicKey"
        PrivateKey: !Ref "PrivateKey"
      ProviderSettings:
        RegionName: !Ref ClusterRegionUppercase
        ProviderName: "SERVERLESS"
      ProjectID: !Ref "AtlasProject"
      Name: !Sub ${EnvironmentName}-${BeName}-Serverless
```

### Actual Behavior
The serverless instance creates fine, however when cloudformation attempts to build the outputs it fails

I have tried the following outputs with their associated errors listed below:

1. As listed in Documentation:
```
  MongoDBAtlasConnectionStringsSrv:
    Condition: IsNotProduction
    Description: "Hostname for mongodb+srv:// connection string"
    Value: !GetAtt "AtlasServerless.ConnectionStrings"
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName","ConnectionStringsSrv" ] ]
```

Error:
Unable to retrieve ConnectionStrings attribute for MongoDB::Atlas::ServerlessInstance, with error message The next fields are required ProjectID ApiKeys.PrivateKey ApiKeys.PublicKey

2. As listed in Documentation:
```
  MongoDBAtlasConnectionStringsSrv:
    Condition: IsNotProduction
    Description: "Hostname for mongodb+srv:// connection string"
    Value: !GetAtt "AtlasServerless.SrvConnectionString"
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName","ConnectionStringsSrv" ] ]
```

Error:
Requested attribute SrvConnectionString does not exist in schema for MongoDB::Atlas::ServerlessInstance

3. Assumed meaning of documentation:
```
  MongoDBAtlasConnectionStringsSrv:
    Condition: IsNotProduction
    Description: "Hostname for mongodb+srv:// connection string"
    Value: !GetAtt "AtlasServerless.ConnectionStrings.SrvConnectionString"
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName","ConnectionStringsSrv" ] ]
```

Error:
Requested attribute ConnectionStrings.SrvConnectionString does not exist in schema for MongoDB::Atlas::ServerlessInstance

4. Derived from Atlas Cluster documentation and underling API

```
  MongoDBAtlasConnectionStringsSrv:
    Condition: IsNotProduction
    Description: "Hostname for mongodb+srv:// connection string"
    Value: !GetAtt "AtlasServerless.ConnectionStrings.StandardSrv"
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName","ConnectionStringsSrv" ] ]
```

Error:
Requested attribute ConnectionStrings.StandardSrv must be a readonly property in schema for MongoDB::Atlas::ServerlessInstance
