### ISSUE TITLE
MongoDB::Atlas::Cluster doesn't expose all ProviderSettings available in Atlas API

### ISSUE THREAD

**Issue by azec-pdx** [mongodb/mongodbatlas-cloudformation-resources#22]
After creating resources:
* project
* db user
I was going to stack Cluster via CloudFormation. Kept failing on specification of cluster tier:
* per Atlas docs of enumerations for available instance sizes -  they don’t allow `M0 Sandbox` through MongoDB Atlas API at all (these are FREE and allowed only through UI)

Then started reading https://docs.atlas.mongodb.com/reference/api/clusters-create-one/
and found this really interesting:

> **providerSettings.instanceSizeName**
```
M2 and M5 clusters are multi-tenant deployments. 
You must set providerSettings.providerName to TENANT and specify the cloud service provider in providerSettings.backingProviderName.
```

Looking at [current spec](https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/master/cluster/mongodb-atlas-cluster.json#L206-L232) of `MongoDB::Atlas::Cluster` , *CloudFormation property `ProviderSettings` DOES NOT allow specifying `ProviderName`*, only `BackingProviderName` property which is not enough to provision M2 and M5 tier clusters.

This creates constraint that minimum possible tier that can be provisioned through CloudFormation  (and `AWS` provider - duuh ) is M10 Cluster.

I am curious if this is "by design" and intentional business decision vs. implementation opportunity? Answer to that question might determine if this issue should be treated as feature-request or canceled.  

Additionally , I can see that [example for cluster](https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/master/examples/cluster/cluster.json#L46) is using also M10. 
However, the same example is using `ProviderName` as top-level property on resource [here](https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/master/examples/cluster/cluster.json#L37), although it is nowhere specified in JSON Schema for `MongoDB::Atlas::Cluster` and interestingly I did have it in my template (by pure copy-paste) and it didn't make resource fail :) 

SUMMARY: 
1. There may be opportunity to expand `ProviderSettings` 
2. There is opportunity to clean up examples for `MongoDB::Atlas::Cluster`

**Comment by themantissa** [comment]
@azec-pdx  I'll respond on what I can but as the README notes this is still beta so it's safe to expect some issues until we can move forward w/ more development.    

The m10 clusters and up is to provide a simpler first experience, as you saw the underlying API is slightly different when configuring M2/M5.   If development continues we'll likely add in coverage for all options in the underlying API, similar to what we've done for Terraform.

**Comment by Zuhairahmed** [comment]
@azec-pdx we have refreshed MongoDB Atlas resources and published to AWS CFN Third Party Public Registry in all 22 AWS regions where MongoDB Atlas is currently available in. Can you double check now if this has resolved your issue?

**Comment by Zuhairahmed** [comment]
Closing out this issue, but feel free to re-open in case if you need anything else. Thank you.

**Comment by carthagan** [comment]
This has not resolved the issue, an invalid reauest is returned as follows:
`400 (request "INVALID_ENUM_VALUE") An invalid enumeration value M0 was specified`

Here is the configuration in AWS CloudFormation:
```
  AtlasCluster:
    Type: 'MongoDB::Atlas::Cluster'
    Properties:
      ProjectId: !GetAtt 
        - AtlasProject
        - Id
      Name: !Ref AtlasClusterName
      Profile: !Ref ProfileKey
      ClusterType: REPLICASET
      ReplicationSpecs:
        - NumShards: '1'
          AdvancedRegionConfigs:
            - ElectableSpecs:
                EbsVolumeType: STANDARD
                InstanceSize: M0
                NodeCount: '3'
              RegionName: US_EAST_1
```
