### ISSUE TITLE
Race condition? - when creating CustomDBRole and DatabaseUser we fail with ATLAS_CUSTOM_ROLE_NOT_FOUND

### ISSUE THREAD

**Issue by arielbeckjit** [mongodb/mongodbatlas-cloudformation-resources#599]
### CloudFormation Template 

```
"MongoMyRole": {
      "Type": "MongoDB::Atlas::CustomDBRole",
      "Properties": {
        "ProjectId": "<project_id>",
        "Profile": "<profile>",
        "RoleName": "my-role",
        "Actions": [
          {
            "Action": "FIND",
            "Resources": [
              {
                "Collection": "col",
                "DB": "db"
              }
            ]
          }
        ]
      }
    },
    "MongoMyUser": {
      "Type": "MongoDB::Atlas::DatabaseUser",
      "Properties": {
        "AWSIAMType": "ROLE",
        "ProjectId": "<project_id>",
        "Profile": "<profile>",
        "DatabaseName": "$external",
        "Username": {
          "Fn::Sub": "arn:aws:iam::${AWS::AccountId}:role/my-iam-role"
        },
        "Roles": [
          {
            "RoleName": "my-role",
            "DatabaseName": "admin"
          }
        ]
      },
      "DependsOn": [
        "MongoMyRole"
      ]
    },
```

We deploy it using serverless framework:
```
    MongoMyRole:
      Type: MongoDB::Atlas::CustomDBRole
      Properties:
        ProjectId: <project_id>
        Actions:
          - Action: FIND
            Resources:
              - Collection: col
                DB: db
        RoleName: my-role
        Profile: <profile>
    MongoMyUser:
      Type: MongoDB::Atlas::DatabaseUser
      Properties:
        Username: arn:aws:iam::#{AWS::AccountId}:role/my-iam-role
        AWSIAMType: ROLE
        ProjectId: <project>
        Profile: <profile>
        DatabaseName: "$external"
        Roles:
          - RoleName: my-role
            DatabaseName: "admin"
      DependsOn: [ MongoMyRole ]
```

### Steps to Reproduce
Create a bunch of role / DB pairs (we have around 20) - and try to deploy it.
note - we use serverless framework to deploy

### Expected Behavior
role and users should be created with no errors

### Actual Behavior
Error occurs, then i need to deploy again (race condition that it takes time to really create the role?)
this is the error i get:
` An error occurred: MongoMyRole - Resource handler returned message: "Error creating resource : POST https://cloud.mongodb.com/api/atlas/v1.0/groups/<project>/customDBRoles/roles: 404 (request "ATLAS_CUSTOM_ROLE_NOT_FOUND") The specified custom db role my-role does not exist." (RequestToken: 1b76ca8b-16df-172e-efa9-59d9eaa710c5, HandlerErrorCode: NotFound).
`

**Comment by Adelmar92** [comment]
hello! @arielbeckjit i see you are creating a MongoDB role, but in the user you are specifying AWSIAMType: ROLE, it should be something like this:

``` yaml
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template creates a cluster on the MongoDB Atlas API and set the Network Peering.
Resources:
  MongoMyRole:
    Type: MongoDB::Atlas::CustomDBRole
    Properties:
      ProjectId: projid
      Actions:
        - Action: FIND
          Resources:
            - Collection: col
              DB: db
      RoleName: my-role
      Profile: default
  MongoMyUser:
    Type: MongoDB::Atlas::DatabaseUser
    Properties:
      Username: testUserName
      Password: pass
      ProjectId: projid
      Profile: default
      DatabaseName: admin
      Roles:
        - RoleName: my-role
          DatabaseName: admin
    DependsOn: [MongoMyRole]
```
