### ISSUE TITLE
Unable to whitelist AWS Cloudformation

### ISSUE THREAD

**Issue by teuber789** [mongodb/mongodbatlas-cloudformation-resources#87]
### Background
I'm trying to create a Cloudformation stack to stand up a Mongo cluster using registered Mongo private resources. I was able to use the `cfn-submit-helper.sh` script to build and submit all the private resources without any trouble. The resources register without any problem and appear to be working.

I've also created a CF template describing a cluster deploy. I basically just copied [the quickstart template](https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/master/quickstart-mongodb-atlas/templates/mongodb-atlas.template.yaml) and made some slight modifications:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Stack describing a MongoDB cluster for the rest API.
Metadata: <omitted for brevity>
Parameters:
  PublicKey:
    Type: String
    Description: Required. Your MongoDB Cloud Public API Key.
  PrivateKey:
    Type: String
    Description: Required. Your MongoDB Cloud Private API Key.
  OrgId:
    Type: String
    Description: Required. Your MongoDB Cloud Organization Id.
  ProjectName:
    Type: String
    Description: Required. The name of the project.
  ClusterName:
    Type: String
    Description: Required. The name of the cluster as it appears in Atlas. Once the cluster is created,
      its name cannot be changed.
  ClusterInstanceSize:
    Type: String
    Description: Required. The size of the Atlas cluster to spin up. Atlas provides different cluster tiers, each with a default storage capacity and RAM size. The cluster you select is used for all the data-bearing hosts in your cluster tier. See https://docs.atlas.mongodb.com/reference/amazon-aws/#amazon-aws.
    AllowedValues: <omitted for brevity>
  ClusterRegion:
    Type: String
    Description: Required. The AWS Region where the Atlas DB Cluster will run.
    AllowedValues: <omitted for brevity>
  ClusterMongoDBMajorVersion:
    Type: String
    Description: Required. The version of MongoDB that you want the new cluster to run.
    AllowedValues:
    - "3.6"
    - "4.0"
    - "4.2"
    - "4.4"
  DatabaseUserRoleDatabaseName:
    Type: String
    Description: Database User Role Database Name
Resources:
  AtlasApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${AWS::StackName}-ApiKey-Secret"
      Description: MongoDB Atlas API Key
      #
      # { "PublicKey" : "xxx", "PrivateKey", "yyy", "OrgId": "zzz" }
      #
      SecretString: !Join ['', ['{"PublicKey":"', !Ref "PublicKey",'", "PrivateKey":"', !Ref "PrivateKey", '", "OrgId":"', !Ref "OrgId", '"}'] ]
      Tags:
      - Key: mongodb-atlas-quickstart-stack
        Value: !Sub "${AWS::StackName}"
  AtlasIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
          Action: 'sts:AssumeRole'
  AtlasProject:
    Type: MongoDB::Atlas::Project
    DependsOn: AtlasIAMRole
    Properties:
      OrgId: !Ref "OrgId"
      ApiKeys:
        PublicKey:  !Ref "PublicKey"
        PrivateKey: !Ref "PrivateKey"
      Name: !Ref "ProjectName"
  AtlasProjectIPAccessList:
    Type: MongoDB::Atlas::ProjectIpAccessList
    DependsOn: AtlasProject
    Properties:
      ProjectId: !Ref "AtlasProject"
      ApiKeys:
        PublicKey:  !Ref "PublicKey"
        PrivateKey: !Ref "PrivateKey"
      AccessList:
      - IPAddress: "0.0.0.0/1"
        Comment: "Testing open all ips"
  AtlasCluster:
    Type: MongoDB::Atlas::Cluster
    DependsOn: AtlasProject
    Properties:
      ApiKeys:
        PublicKey:  !Ref "PublicKey"
        PrivateKey: !Ref "PrivateKey"
      ProjectId: !Ref "AtlasProject"
      Name: !Ref "ClusterName"
      MongoDBMajorVersion: !Ref "ClusterMongoDBMajorVersion"
      ReplicationFactor: 3
      NumShards: 1
      ProviderSettings:
        ProviderName: "AWS"
        InstanceSizeName: !Ref "ClusterInstanceSize"
        RegionName: !Ref "ClusterRegion"
  AtlasDatabaseUser:
    Type: MongoDB::Atlas::DatabaseUser
    DependsOn: AtlasCluster
    Properties:
      ProjectId: !Ref "AtlasProject"
      ApiKeys:
        PublicKey:  !Ref "PublicKey"
        PrivateKey: !Ref "PrivateKey"
      Username: !GetAtt "AtlasIAMRole.Arn"
      DatabaseName: "$external"
      AWSIAMType: "ROLE"
      Roles:
      - RoleName: "readWrite"
        DatabaseName: !Ref "DatabaseUserRoleDatabaseName"
      Scopes:
      - Name: !Sub "${AWS::StackName}"
        Type: "CLUSTER"
Outputs: <omitted for brevity>
```

### The problem
The problem is that when I run my Cloudformation template, the `AtlasProject` resource fails to create with the following error:

```json
{
    "level": "debug",
    "msg": "Create - error: POST https://cloud.mongodb.com/api/atlas/v1.0/groups: 403 (request \"Forbidden\") IP address 18.118.114.43 is not allowed to access this resource.",
    "time": "2021-06-12T14:39:15Z"
}
```

`18.118.114.43` is the address of the Amazon Cloudformation server building the stack. Obviously, I can't whitelist this address in my Atlas organization's IP access lists because I don't know it before the stack is run.

I made the following attempts to fix the problem:

* I added `18.118.114.43` to my Atlas organization's whitelist. This failed because the IP address changed each time the stack was run (i.e., `52.15.211.239` and `18.191.254.107`)
* I attempted to add `0.0.0.0/0` to my Atlas organization's whitelist. However, that failed with the following error: `The address 0.0.0.0/0 cannot be added to access lists.`

At this point, it seems like the only way to fix this problem is to whitelist [Amazon's block of IP addresses](https://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html) for my AWS region if I want the CF templates to work. This is not only impractical, it's insecure.

### Expected behavior
After I've built and registered the MongoDB Cloudformation resources in my AWS organization's private registry, I should be able to use them in CF templates without whitelisting all of Amazon's IP addresses.

The documentation should explain how to get around this issue. Right now all it says is, "You should allow API access for the IP address from which the acceptance test runs", which isn't very meaningful because that's not the same IP address that CF will be using to provision the stack.

Any help is much appreciated.
