### ISSUE TITLE
Enum related cluster creation error

### ISSUE THREAD

**Issue by StefanWachter1507** [mongodb/mongodbatlas-cloudformation-resources#900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### CFN Resource version

v2.0.0

### CFN Resource Region

eu-central-1

### Current Behavior

Cluster creation using the CfnCluster CDK construct fails with the following error:

```
 Resource handler returned message: "https://cloud.mongodb.com/api/atlas/v2/groups/xxx/clusters POST: HTTP 400 Bad Request (Error code: "INVALID_ENUM_VALUE") Detail: An invalid enumeration value  was specified. Reason: Bad Request. Params: []" (RequestToken: c8e86d90-7bc3-b702-a78c-605e34649745, HandlerErrorCode: InvalidRequest)
```
The details message contains two spaces between "value" and "was" which suggests that an empty string was sent as an enum value.

I checked the enum valued properties in `CfnClusterProps`. I found that the error disappears when `ebsVolumeType: 'STANDARD'` is set in the `electableSpecs` property. Setting the `ebsVolumeType` property should not be necessary. The [MongoDB Atlas Admin API/createCluster](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Clusters/operation/createCluster) operation documents the `ebsVolumeType` property to have `'STANDARD'` as default.

I guess that the `CfnCluster` resource sends an empty string for the `ebsVolumeType` when that property is not set in `CfnClusterProps`. Unfortunately, the error does not always happen. I could create clusters without having that property set. However, within a specific account and specifc `CfnClusterProps` this error is reproducable.

### CFN template to reproduce the issue

```yaml
"instance": {
   "Type": "MongoDB::Atlas::Cluster",
   "Properties": {
    "BackupEnabled": true,
    "ClusterType": "REPLICASET",
    "DiskSizeGB": 10,
    "ProjectId": {
     "Ref": "SsmParameterValuepaymentmongoatlasprojectIdC96584B6F00A464EAD1953AFF4B05118Parameter"
    },
    "Name": "payment-live",
    "ReplicationSpecs": [
     {
      "NumShards": 1,
      "AdvancedRegionConfigs": [
       {
        "RegionName": "EU_CENTRAL_1",
        "ElectableSpecs": {
         "InstanceSize": "M10",
         "NodeCount": 3
        },
        "Priority": 7
       }
      ]
     }
    ]
   }
  }
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
